from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("png-transparent-and-eye-files-folder-folders-view-files-and-folders-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font-family: Noto Sans SC;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.label_video = QtWidgets.QLabel(self.centralwidget)
        self.label_video.setGeometry(QtCore.QRect(250, 90, 521, 381))
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(0, 10, 261, 71))
        self.label_logo.setStyleSheet("background-color:none")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("cooltext434407997559181.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.comboBox_choosecam = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_choosecam.setGeometry(QtCore.QRect(20, 270, 211, 31))
        self.comboBox_choosecam.setStyleSheet("color: white")
        self.comboBox_choosecam.setObjectName("comboBox_choosecam")
        self.comboBox_choosecam.addItem("")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 231, 31))
        self.label_11.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_11.setObjectName("label_11")
        self.pushButton_fast = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fast.setGeometry(QtCore.QRect(10, 120, 101, 23))
        self.pushButton_fast.setStyleSheet("color: white")
        self.pushButton_fast.setObjectName("pushButton_fast")
        self.pushButton_accurate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_accurate.setGeometry(QtCore.QRect(120, 120, 101, 23))
        self.pushButton_accurate.setStyleSheet("color: white")
        self.pushButton_accurate.setObjectName("pushButton_accurate")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 231, 41))
        self.label_10.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_10.setObjectName("label_10")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(50, 220, 131, 31))
        self.label_1.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_1.setObjectName("label_1")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 240, 211, 31))
        self.label_9.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 350, 91, 31))
        self.label_2.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.pushButton_beginlearn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_beginlearn.setGeometry(QtCore.QRect(10, 150, 211, 23))
        self.pushButton_beginlearn.setStyleSheet("color: white")
        self.pushButton_beginlearn.setObjectName("pushButton_beginlearn")
        self.pushButton_openvid = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openvid.setGeometry(QtCore.QRect(20, 430, 211, 23))
        self.pushButton_openvid.setStyleSheet("color: white")
        self.pushButton_openvid.setObjectName("pushButton_openvid")
        self.label_current_status = QtWidgets.QLabel(self.centralwidget)
        self.label_current_status.setGeometry(QtCore.QRect(250, 470, 531, 41))
        self.label_current_status.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_current_status.setObjectName("label_current_status")
        self.comboBox_search = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_search.setGeometry(QtCore.QRect(250, 540, 231, 31))
        self.comboBox_search.setStyleSheet("color: white")
        self.comboBox_search.setObjectName("comboBox_search")
        self.comboBox_search.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 510, 111, 31))
        self.label_6.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_6.setObjectName("label_6")
        self.pushButton_screenshot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_screenshot.setGeometry(QtCore.QRect(640, 540, 131, 31))
        self.pushButton_screenshot.setStyleSheet("color: white")
        self.pushButton_screenshot.setObjectName("pushButton_screenshot")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 395, 211, 31))
        self.label_8.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_8.setObjectName("label_8")
        self.comboBox_chsborderclr = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_chsborderclr.setGeometry(QtCore.QRect(290, 40, 201, 31))
        self.comboBox_chsborderclr.setStyleSheet("color: white")
        self.comboBox_chsborderclr.setObjectName("comboBox_chsborderclr")
        self.comboBox_chsborderclr.addItem("")
        self.comboBox_chsborderclr.addItem("")
        self.comboBox_chsborderclr.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 10, 131, 31))
        self.label_4.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 10, 131, 31))
        self.label_5.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_5.setObjectName("label_5")
        self.comboBox_chstextclr = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_chstextclr.setGeometry(QtCore.QRect(530, 40, 201, 31))
        self.comboBox_chstextclr.setStyleSheet("color: white")
        self.comboBox_chstextclr.setObjectName("comboBox_chstextclr")
        self.comboBox_chstextclr.addItem("")
        self.comboBox_chstextclr.addItem("")
        self.comboBox_chstextclr.addItem("")
        self.pushButton_savecam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_savecam.setGeometry(QtCore.QRect(20, 310, 211, 23))
        self.pushButton_savecam.setStyleSheet("color: white")
        self.pushButton_savecam.setObjectName("pushButton_savecam")
        self.checkBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox1.setGeometry(QtCore.QRect(20, 380, 201, 17))
        self.checkBox1.setStyleSheet("background-color: none;\n"
"color: white")
        self.checkBox1.setObjectName("checkBox1")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 515, 211, 31))
        self.label_12.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 470, 131, 31))
        self.label_3.setStyleSheet("background-color: none;\n"
"color: white")
        self.label_3.setObjectName("label_3")
        self.pushButton_openimg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openimg.setGeometry(QtCore.QRect(20, 550, 211, 23))
        self.pushButton_openimg.setStyleSheet("color: white")
        self.pushButton_openimg.setObjectName("pushButton_openimg")
        self.checkBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox2.setGeometry(QtCore.QRect(20, 500, 201, 17))
        self.checkBox2.setStyleSheet("background-color: none;\n"
"color: white")
        self.checkBox2.setObjectName("checkBox2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VisionSense"))
        self.comboBox_choosecam.setItemText(0, _translate("MainWindow", "Выбрать камеру"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Модель обучения</span></p></body></html>"))
        self.pushButton_fast.setText(_translate("MainWindow", "Быстрый"))
        self.pushButton_accurate.setText(_translate("MainWindow", "Точный"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Режим анализа</span></p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">Анализ видеокамеры</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Текущая камера"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">Анализ видео</span></p></body></html>"))
        self.pushButton_beginlearn.setText(_translate("MainWindow", "Начать"))
        self.pushButton_openvid.setText(_translate("MainWindow", "Открыть"))
        self.label_current_status.setText(_translate("MainWindow", "Статус: Ожидание начала обучения..."))
        self.comboBox_search.setItemText(0, _translate("MainWindow", "Все"))
        self.label_6.setText(_translate("MainWindow", "Поиск объектов"))
        self.pushButton_screenshot.setText(_translate("MainWindow", "Сделать скриншот"))
        self.label_8.setText(_translate("MainWindow", "Выберите видео:"))
        self.comboBox_chsborderclr.setItemText(0, _translate("MainWindow", "Зеленый"))
        self.comboBox_chsborderclr.setItemText(1, _translate("MainWindow", "Красный"))
        self.comboBox_chsborderclr.setItemText(2, _translate("MainWindow", "Синий"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">Цвет рамки</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">Цвет текста</span></p></body></html>"))
        self.comboBox_chstextclr.setItemText(0, _translate("MainWindow", "Зеленый"))
        self.comboBox_chstextclr.setItemText(1, _translate("MainWindow", "Красный"))
        self.comboBox_chstextclr.setItemText(2, _translate("MainWindow", "Синий"))
        self.pushButton_savecam.setText(_translate("MainWindow", "Начать запись"))
        self.checkBox1.setText(_translate("MainWindow", "Сохранять видео"))
        self.label_12.setText(_translate("MainWindow", "Выберите изображение:"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">Анализ изображения</span></p></body></html>"))
        self.pushButton_openimg.setText(_translate("MainWindow", "Открыть"))
        self.checkBox2.setText(_translate("MainWindow", "Сохранять изображение"))